#!/usr/bin/env bash

##### set symlinks for dotFiles #####
# Alacritty
ln -sf $HOME/dotFiles/alacritty/* $HOME/
# Bash
ln -sf $HOME/dotFiles/* $HOME/
# Bin [user]
ln -sfn $HOME/dotFiles/bin $HOME/bin
# Homebrew
ln -sf $HOME/dotFiles/homebrew/* $HOME/
# Git
ln -sf $HOME/dotFiles/git/* $HOME/
# GMSH
ln -sf $HOME/dotFiles/gmsh/* $HOME/
# iTerm2
# ln -sf $HOME/dotFiles/iterm/* #<path/to/iterm/conf>
# Lepton
ln -sf $HOME/dotFiles/lepton/* $HOME/
# Neofetch
ln -sf $HOME/dotFiles/neofetch/* $HOME/.config/neofetch/
# Tmux
ln -sf $HOME/dotFiles/tmux/* $HOME/
# Vim
ln -sf $HOME/dotFiles/vim/!(myPlugins) $HOME/ # link everything but the plugins directory -- requires shopt -s extglob
ln -sfn $HOME/dotFiles/vim/myPlugins $HOME/.vim/myPlugins # manually link the .vim/myPlugins directory
# VS Code
ln -sf $HOME/dotFiles/vscode/* "$HOME/Library/Application Support/Code/User/"
