version: "3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=479
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /home/estysdesu/plexData:/config
      - /home/estysdesu/plexData/tv:/tv
      - /home/estysdesu/plexData/movies:/movies
      - /home/estysdesu/plexData/transcode:/transcode
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: unless-stopped
